language: node_js
node_js:
- "10.13"

env:
- SLS_DEBUG=* TWITTER_CALLBACK_URL=https://remindmeofthis.app/_/completetwittersignin EXTERNAL_URL=remindmeofthis.app

cache:
  directories:
  - node_modules

install: npm i && npm i -g serverless

stages:
- name: predeploy
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: predeploy
    script: npm run test-unit
    name: "Unit tests"

  - stage: predeploy
    script: npm run test
    name: "Feature tests"

  - stage: predeploy
    script: npm run lint
    name: "Lint"

  - stage: deploy
    env: LAMBDA_FUNCTION_NAME=RemindMeOfThisTweet-dev-remind
    before_script:
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -b ~/bin/aws
    - export PATH=~/bin:$PATH
    script: |
      sls deploy && \
      (aws --region us-east-1 lambda get-policy  --function-name RemindMeOfThisTweet-dev-remind \
      || aws --region us-east-1 lambda add-permission --function-name RemindMeOfThisTweet-dev-remind --statement-id InvokePermission --principal events.amazonaws.com --action lambda:InvokeFunction)
